import { Desafio, DesafioNivel2, DesafioNivel3e4 } from "../interfaces/interfaces";

export function textos1(data: Desafio) {
    const textos1 = [
        { id: 0, name: null, person: 2, texto: `Ana is a second-year Computer Science student.\n\nShe did a project on Free Software (SL) and became very interested in the topic, wanting to dive deeper to potentially contribute in the future and join a SL community.` },
        { id: 1, name: null, person: 1, texto: `Maria has developed several research projects related to SL projects and communities and has worked on some, making important contributions. Maria loves talking about this universe to others and sharing the knowledge she has acquired over the years.` },
        { id: 2, name: null, person: 3, texto: `Since Ana wants to learn more about SL projects and Maria loves teaching, they arranged a meeting so Maria can help Ana understand more about this world.` },
        { id: 3, name: "Maria", person: 3, texto: `Hello Ana, how are you?` },
        { id: 4, name: "Ana", person: 3, texto: "I'm doing great, and how are you?" },
        { id: 5, name: "Maria", person: 3, texto: "Very well. Are you ready to start our journey in search of knowledge?" },
        { id: 6, name: "Ana", person: 3, texto: "Of course, I'm very excited.\nThis topic really interests me." },
        { id: 7, name: "Maria", person: 3, texto: "I'm also really excited. Talking about Free Software projects is a lot of fun for me." },
        { id: 8, name: "Ana", person: 3, texto: "That's great, at least helping you won't be such a big problem for me." },
        { id: 9, name: "Maria", person: 3, texto: "Of course not, but let's get started. First, I'll explain how our meeting will work.\n\nReady to begin?" },
        { id: 10, name: "Maria", person: 3, texto: "Let's go, in this meeting, we will see a scenario that occurred within an SL project.." },
        { id: 11, name: "Maria", person: 3, texto: "More specifically, a problem that happened and was solved by the community, okay." },
        { id: 12, name: "Ana", person: 3, texto: "Okay, sounds good!" },
        { id: 13, name: "Maria", person: 3, texto: `The problem we're going to discuss today occurred within the ${data.nomeProjeto} project. \nHave you heard of it?` },
        { id: 14, name: "Maria", person: 3, texto: `Alright, let's take a look at some information about this project.` },
        { id: 15, name: "Ana", person: 3, texto: "Okay!" },
        { id: 16, name: "Maria", person: 3, texto: "That's great, but just to remind you, let's see some information about this project, ok." },
        { id: 17, name: "Ana", person: 3, texto: "Ok!" },
        { id: 18, name: "Maria", person: 3, texto: `${data.dadosProj}` },
        { id: 19, name: "Maria", person: 3, texto: `Well, I think you now have a general idea of what the project is about, right? Now, let's first look at the conceptual part of the problem.` },
        { id: 20, name: "Ana", person: 3, texto: "Yes, that's fine!" },
        { id: 21, name: 'Maria', person: 3, texto: `${data.descProblema}` },
        { id: 22, name: "Maria", person: 3, texto: `Would you like me to repeat the information?` },
        { id: 23, name: "Maria", person: 3, texto: `Alright, let's go. \n${data.descProblema}` },
        { id: 24, name: "Maria", person: 3, texto: `Now, let's make things clearer. Let's see how this problem occurred in practice within the ${data.nomeProjeto} project.` },
        { id: 25, name: "Ana", person: 3, texto: "Okay, let's go!" },
        { id: 26, name: 'Maria', person: 3, texto: `${data.contextoProblema}` },
        { id: 27, name: "Maria", person: 3, texto: `To help you, I have some supplementary material on this problem. How about taking a look at it and trying to understand it better?` },
        { id: 28, name: "Maria", person: 3, texto: `Whenever you're ready, we can continue.` },
        { id: 29, name: "Maria", person: 3, texto: `So we can continue, we've already seen the problem in a general way, and we saw how it occurred in the ${data.nomeProjeto} project, but how was this problem solved by the community?` },
        { id: 30, name: "Maria", person: 3, texto: `Let's see that now!` },
        { id: 31, name: "Maria", person: 3, texto: `Let's go!!` },
        { id: 32, name: "Maria", person: 3, texto: `${data.solucao}` },
        { id: 33, name: "Maria", person: 3, texto: `But now I have a challenge for you. You didn’t think it would just be about listening to me, did you?` },
        { id: 34, name: "Ana", person: 3, texto: "Okay!" },
        { id: 35, name: "Maria", person: 3, texto: `I already told you how they solved the problem, now you must organize the steps of the solution.` },
        { id: 36, name: "Maria", person: 3, texto: `Unfortunately, you had your three attempts, and your answer is not correct, but the important thing is to try.` },
        { id: 37, name: "Maria", person: 3, texto: `Don’t give up, you'll get it right next time.` },
        { id: 38, name: "Maria", person: 3, texto: `That's right, congratulations, your answer is correct.` },
        { id: 39, name: "Maria", person: 3, texto: `I'll show you again how the steps are correctly organized.` },
        { id: 40, name: "Maria", person: 3, texto: `${data.etapasSolucao}` },
        { id: 41, name: "Maria", person: 3, texto: `Let's move on. I'll show you the impacts that solving this type of problem can have on the project.` },
        { id: 42, name: "Ana", person: 3, texto: `Alright, let's go!` },
        { id: 43, name: "Maria", person: 3, texto: `${data.resultado}` },
        { id: 44, name: "Maria", person: 3, texto: `So, what did you think? Did you learn anything from our meeting?` },
        { id: 45, name: "Maria", person: 3, texto: `That's great, I'm really happy to be helping you on this journey.` },
    ];

    return textos1;
}

export function textos2(data: DesafioNivel2, feedback: string, linhas: string[]) {
    const textos2 = [
        { id: 0, name: null, person: 2, texto: `Ana just graduated and is working at a company as a Junior Developer. Since college, when she did a project on SL projects, she became interested in the subject. She even met with Maria to get more information, but ended up not having time to delve deeper after their meeting.` },
        { id: 1, name: null, person: 1, texto: `Maria decided to help Ana once again and encourage her to continue studying SL projects.` },
        { id: 2, name: null, person: 2, texto: `Since Ana is willing to try again, she and Maria scheduled another meeting to talk about SL projects.` },
        { id: 3, name: 'Maria', person: 3, texto: `Hello Ana, how are you?` },
        { id: 4, name: 'Ana', person: 3, texto: `I'm great, and you?` },
        { id: 5, name: 'Maria', person: 3, texto: `I'm very well, ready to start?` },
        { id: 6, name: 'Maria', person: 3, texto: `So let's go. \nThe problem we are going to see today happened in the ${data.nomeProjeto} project. Have you heard of this project?` },
        { id: 7, name: "Maria", person: 3, texto: `Okay, let's take a look at it then.` },
        { id: 8, name: "Ana", person: 3, texto: `Okay!` },
        { id: 9, name: "Maria", person: 3, texto: `Very good, let's just recall its objectives, okay?` },
        { id: 10, name: "Ana", person: 3, texto: `Okay!` },
        { id: 11, name: "Maria", person: 3, texto: `${data.dadosProj}` },
        { id: 12, name: "Maria", person: 3, texto: `Well, I think you got a general idea of what the project is about, right? You can still research more about it later.` },
        { id: 13, name: "Ana", person: 3, texto: `Okay, cool!` },
        { id: 14, name: "Maria", person: 3, texto: `Now let's first look at the conceptual part of the problem we are going to study.` },
        { id: 15, name: "Ana", person: 3, texto: `Alright!` },
        { id: 16, name: "Maria", person: 3, texto: `${data.descProblema}` },
        { id: 17, name: "Maria", person: 3, texto: `Would you like me to repeat this information?` },
        { id: 18, name: "Maria", person: 3, texto: `Alright. Here we go: \n${data.descProblema}` },
        { id: 19, name: "Maria", person: 3, texto: `Now let's see this problem in practice, within the ${data.nomeProjeto} project.` },
        { id: 20, name: "Ana", person: 3, texto: `Okay, let's go!` },
        { id: 21, name: "Maria", person: 3, texto: `${data.contextoProblema}` },
        { id: 22, name: "Maria", person: 3, texto: `Is everything okay so far?` },
        { id: 23, name: "Maria", person: 3, texto: `To help you, I have some supplementary material on this problem. How about taking a look and trying to understand it better?` },
        { id: 24, name: "Ana", person: 3, texto: `Okay, let's do it!` },
        { id: 25, name: "Maria", person: 3, texto: `Whenever you're ready, we can continue.` },
        { id: 26, name: "Maria", person: 3, texto: `Great, then we can continue. Just to recap, we saw the problem in a general way and how it occurred within the ${data.nomeProjeto} project. But how do you think this problem was solved by the community that contributes to the project?` },
        { id: 27, name: "Maria", person: 3, texto: `Let's find out now!` },
        { id: 28, name: "Ana", person: 3, texto: `Let's go!` },
        { id: 29, name: "Maria", person: 3, texto: `${data.solucao}` },
        { id: 30, name: "Maria", person: 3, texto: `I will present the steps to you, but I have a challenge: you need to complete the solution steps.` },
        { id: 31, name: "Maria", person: 3, texto: `Here are the steps, but steps 2 and 4 are missing. What information should be included in these steps?` },
        { id: 32, name: "Maria", person: 3, texto: `Step 1: ${linhas[0]}\n\nStep 3: ${linhas[2]}` },
        { id: 33, name: "Maria", person: 3, texto: `Now I'm going to ask a more experienced friend to check if your proposed solution is correct, okay? Please wait until my friend responds and gives you feedback.` },
        { id: 34, name: "Maria", person: 3, texto: feedback }, // name: null, person: 0, dynamic text (feedback)
        { id: 35, name: "Maria", person: 3, texto: `Unfortunately, your answer is not correct, but the important thing is that you tried.` },
        { id: 36, name: "Maria", person: 3, texto: `That's right, congratulations! Your answer is correct.` },
        { id: 37, name: "Maria", person: 3, texto: `Let me show you again how the complete steps should look.` },
        { id: 38, name: "Maria", person: 3, texto: `${data.etapasSolucao}` }, // name: null, person: 0, dynamic text (solution steps)
        { id: 39, name: "Maria", person: 3, texto: `Let's move on. I'm going to show you the impacts that solving this type of problem can have on the project.` },
        { id: 40, name: "Ana", person: 3, texto: `Alright, let's go.` },
        { id: 41, name: "Maria", person: 3, texto: `${data.resultado}` }, // name: null, person: 0, dynamic text (result)
        { id: 42, name: "Maria", person: 3, texto: `So, what did you think? I’d like you to rate today's content using stars.` },
        { id: 43, name: "Maria", person: 3, texto: `Thank you for leaving your rating, I’m very happy to be helping you on this journey.` }
    ];

    return textos2;
}

export default function textos3(data: DesafioNivel3e4, feedback: string){
    const textos = [
        { id: 1, name: null, person: 3, texto: `Ana was promoted at the company where she works. This company is interested in entering the world of SL projects, but for that, they need to evaluate if it is a good option and understand more about how communities work. Ana has been tasked with leading the project, given her previous contact with the world of SL projects. Therefore, she must study more and later pass on the knowledge she has acquired.` },
        { id: 2, name: null, person: 3, texto: `Maria is back to help Ana once again and encourage her to continue studying SL projects.` },
        { id: 3, name: null, person: 3, texto: `Ana needs Maria's help again, and they have scheduled a meeting to talk about SL projects.` },
        { id: 4, name: "Maria", person: 3, texto: `Hey, Ana, how are you?` },
        { id: 5, name: "Ana", person: 3, texto: `I'm good, and you, how are you?` },
        { id: 6, name: "Maria", person: 3, texto: `I'm great, ready for another challenge?` },
        { id: 7, name: "Maria", person: 3, texto: `Let's go. \nThe problem we will look at today occurred in the project ${data.nomeProjeto}, have you heard of this project?` },
        { id: 8, name: "Maria", person: 3, texto: `Alright, let's look at some information about this project.` },
        { id: 9, name: "Ana", person: 3, texto: `Ok!` },
        { id: 10, name: "Maria", person: 3, texto: `That's great, so let's just recap, okay.` },
        { id: 11, name: "Ana", person: 3, texto: `Ok!` },
        { id: 12, name: "Maria", person: 3, texto: `${data.dadosProj}` },
        { id: 13, name: "Maria", person: 3, texto: `Now that we have an idea about the project we will address, let's first look at the conceptual part of the problem.` },
        { id: 14, name: "Ana", person: 3, texto: `Ok, that's fine.` },
        { id: 15, name: "Maria", person: 3, texto: `${data.descProblema}` },
        { id: 16, name: "Maria", person: 3, texto: `Would you like me to repeat this information?` },
        { id: 17, name: "Maria", person: 3, texto: `Alright. Let's go:` },
        { id: 18, name: "Maria", person: 3, texto: `${data.descProblema}` },
        { id: 19, name: "Maria", person: 3, texto: `Now let's see how this problem occurred in practice, in the project ${data.nomeProjeto}.` },
        { id: 20, name: "Maria", person: 3, texto: `${data.contextoProblema}` },
        { id: 21, name: "Maria", person: 3, texto: `Did you understand up to here?` },
        { id: 22, name: "Maria", person: 3, texto: `To help you, I have some supplementary material about this problem, how about taking a look and trying to understand better?` },
        { id: 23, name: "Ana", person: 3, texto: `Ok, let's go!` },
        { id: 24, name: "Maria", person: 3, texto: `Whenever you're ready, we can continue!` },
        { id: 25, name: "Maria", person: 3, texto: `So let's continue, we've seen the problem in a generic way and how it occurred within the project ${data.nomeProjeto}, but what did the project contributors do to solve the problem?` },
        { id: 26, name: "Maria", person: 3, texto: `Let's see that now!` },
        { id: 27, name: "Ana", person: 3, texto: `Let's go!` },
        { id: 28, name: "Maria", person: 3, texto: `${data.solucao}` },
        { id: 29, name: "Maria", person: 3, texto: `I've already told you how they solved the problem, now you should create the solution steps. Be as detailed as possible.` },
        { id: 30, name: "Maria", person: 3, texto: `You can ask for a hint if necessary.` },
        { id: 31, name: "Maria", person: 3, texto: `Now I will ask for the help of a more experienced friend to check if your proposed solution is correct, okay. Please wait until my friend responds and gives you feedback.` },
        { id: null, name: "Maria", person: 3, texto: `Feedback: ${feedback}` },
        { id: 32, name: "Maria", person: 3, texto: `Unfortunately, your answer is not correct, but the important thing is that you tried.` },
        { id: 33, name: "Maria", person: 3, texto: `That's it, congratulations, your answer is correct.` },
        { id: 34, name: "Maria", person: 3, texto: `I will show you again how the complete steps look.` },
        { id: 35, name: "Maria", person: 3, texto: `${data.etapasSolucao}` },
        { id: 36, name: "Maria", person: 3, texto: `Let's continue, I will show you the impacts that solving this type of problem can have on the project.` },
        { id: 37, name: "Ana", person: 3, texto: `Alright, let's go.` },
        { id: 38, name: "Maria", person: 3, texto: `${data.resultado}` },
        { id: 39, name: "Maria", person: 3, texto: `So, what did you think? Did you learn anything from today's meeting?` },
        { id: 40, name: "Maria", person: 3, texto: `That's a shame.` },
        { id: 41, name: "Maria", person: 3, texto: `That's great, I'm very happy!` },
        { id: 42, name: "Maria", person: 3, texto: `Now I would like to know if you could help me improve the content of my examples. Could you evaluate the content we've seen?` },
        { id: 43, name: "Maria", person: 3, texto: `That's fine, no problem.` },
        { id: 44, name: "Maria", person: 3, texto: `That's great, here is the form for the evaluation.` },
        { id: 45, name: "Maria", person: 3, texto: `Thank you for leaving your evaluation, I'm very happy to be helping you on this journey.` },
        { id: 46, name: "Maria", person: 3, texto: `Thank you for participating in our game.` },
    ];

    return textos;
}

export function textos4(feedback: string){
    const textos = [
        { id: 1, name: "Maria", person: 3, texto: "Ana trabalha na mesma empresa de software há mais de 18 anos, e possui uma vasta experiência. No entanto, está tentando um emprego em uma grande fundação de código aberto, e para conseguir a vaga precisa se aprofundar mais no mundo dos projetos de SL." },
        { id: 2, name: "Maria", person: 3, texto: "Maria está de volta para ajudá-la nessa missão." },
        { id: 3, name: "Maria", person: 3, texto: "E ai, Ana, como vai?" },
        { id: 4, name: "Ana", person: 3, texto: "Estou bem, e você, como vai?" },
        { id: 5, name: "Maria", person: 3, texto: "Estou ótima." },
        { id: 6, name: "Ana", person: 3, texto: "Que bom!" },
        { id: 7, name: "Maria", person: 3, texto: "Hoje vamos fazer algo diferente para encerrarmos nossa jornada juntos. Está preparada?" },
        { id: 8, name: "Maria", person: 3, texto: "Ok, legal. Até aqui eu era responsável por trazer um cenário com um problema que ocorreu em um projeto de SL, e estudávamos esse cenário juntos. Hoje vamos fazer diferente." },
        { id: 9, name: "Maria", person: 3, texto: "Minha proposta é que você explore o mundo dos projetos de SL e crie um exemplo como o que vimos durante nossas interações." },
        { id: 10, name: "Ana", person: 3, texto: "Esse é um grande desafio." },
        { id: 11, name: "Maria", person: 3, texto: "Mas com o que vimos até aqui, acho que vai ser moleza para você." },
        { id: 12, name: "Ana", person: 3, texto: "Está bem, vamos lá." },
        { id: 13, name: "Maria", person: 3, texto: "Para te ajudar vou te fornecer o link de um commit com um cenário e sua missão vai ser entende-lo e criar um exemplo." },
        { id: 14, name: "Ana", person: 3, texto: "Ok." },
        { id: 15, name: "Maria", person: 3, texto: "Aqui está o link, basta clicar para ter acesso ao commit!" },
        { id: 16, name: "Maria", person: 3, texto: "Para criar o exemplo você deve utilizar o formulário disponível neste link. Para acessá-lo é necessário fazer login no sistema" },
        { id: 17, name: "Maria", person: 3, texto: "Para criar o exemplo vou te fornecer algumas diretrizes. Essas diretrizes são encontradas no padrão disponível neste link. Fique atento a elas ao criar seu exemplo." },
        { id: 18, name: "Maria", person: 3, texto: "Para melhorar, você pode pedir a ajuda de outros colegas nessa tarefa." },
        { id: 19, name: "Maria", person: 3, texto: "Boa sorte nesta missão, você tem 7 dias para completar esse desafio." },
        { id: 20, name: "Maria", person: 3, texto: "Agora vou pedir a ajuda de um amigo mais experiente para verificar se a sua proposta de solução está correta, ok. Peço que aguarde até que meu amigo responda, e te devolva um feedback." },
        {id: 21, name: "Maria", person: 3, texto: `Feedback: ${feedback}`},
        { id: 22, name: "Maria", person: 3, texto: "Infelizmente sua resposta não está correta, mas o importante é que você tentou." },
        { id: 23, name: "Maria", person: 3, texto: "Isso aí, parabéns, sua resposta está correta." },
        { id: 24, name: "Maria", person: 3, texto: "Você foi muito bem! E vai alcançar todos os objetivos que deseja." }
      ];
    return textos;
}